export const COUNTRIES_WITH_CITIES: Record<string, string[]> = {
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Miami",
    "San Francisco",
    "Seattle",
    "Boston",
    "Austin",
    "Denver",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
    "Bristol",
    "Liverpool",
    "Leeds",
  ],
  Canada: [
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Edmonton",
  ],
  Germany: [
    "Berlin",
    "Munich",
    "Hamburg",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
  ],
  France: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Florence", "Venice"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö"],
  Norway: ["Oslo", "Bergen", "Trondheim"],
  Denmark: ["Copenhagen", "Aarhus", "Odense"],
  Iran: [
    "Tehran",
    "Isfahan",
    "Shiraz",
    "Mashhad",
    "Tabriz",
    "Karaj",
    "Ahvaz",
    "Kerman",
  ],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
  ],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo", "Nagoya"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Curitiba"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Cancún"],
  Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
  Egypt: ["Cairo", "Alexandria", "Giza"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria"],
  Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Kazan"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"],
};

export const COUNTRY_LIST = Object.keys(COUNTRIES_WITH_CITIES).sort();
